### ISSUE TITLE
support symlinks to the installed commands

### ISSUE THREAD

**Issue by freddrake** [keepertech/appackager#3]
The lib directory is not correctly found; the `abspath` in the generated script produces the absolute path to the symlink rather than the absolute path to the actual script, so the remaining path algebra doesn't work out.

**Comment by wyllys66** [comment]
cool!

**Comment by freddrake** [comment]
> cool!

Heh.  I'd thought this was straightened out long ago, but I guess I'd missed it.  Definitely better than having to keep adding directories to PATH.
